// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Transaction struct {
	ID           uuid.UUID
	Time         pgtype.Timestamptz
	WalletFromID uuid.UUID
	WalletToID   uuid.UUID
	Amount       decimal.Decimal
}

type Wallet struct {
	ID      uuid.UUID
	Balance decimal.Decimal
}
